// Generated by CoffeeScript 1.6.3
(function() {
  $.fn.extend({
    expList: function(options) {
      var opts, self;
      self = $.fn.expList;
      opts = $.extend({}, self.default_options, options);
      return $(this).each(function(i, elem) {
        return self.init(elem, opts);
      });
    }
  });

  $.extend($.fn.expList, {
    default_options: {
      duration: 600,
      enableLinks: true,
      expanded: null,
      collapsed: null
    },
    init: function(elem, opts) {
      var child, childrenList, _fn, _i, _len;
      $(elem).find('ul').hide();
      if (opts.collapsed != null) {
        $(elem).find('li:has(ul)').addClass(opts.collapsed);
      }
      childrenList = $(elem).find('li:has(ul)');
      _fn = function() {
        return $(child).on('click', function(e) {
          var event;
          event = e || window.event;
          $(event.target).closest('li').children('ul').toggle(opts.duration);
          if (opts.expanded != null) {
            $(event.target).closest('li').toggleClass(opts.expanded);
          }
          if (opts.collapsed != null) {
            $(event.target).closest('li').toggleClass(opts.collapsed);
          }
          return event.stopPropagation();
        });
      };
      for (_i = 0, _len = childrenList.length; _i < _len; _i++) {
        child = childrenList[_i];
        _fn();
      }
      if (opts.enableLinks) {
        return $(elem).find('a').off('click').on('click', function(e) {
          var event;
          event = e || window.event;
          return event.stopPropagation();
        });
      }
    }
  });

}).call(this);
